charts/etos/charts/environment_provider/values.yaml, charts/etos/charts/etos-api/values.yaml, charts/etos/charts/suite-starter/values.yaml, charts/etos/templates/_helpers.tpl, charts/etos/values.yaml
fixes #51 
This change sets the default docker production repositories correctly and also makes docker repositories and tags honor the development flag.
N/A
We pull the correct images when deploying a production and/or development release of ETOS
N/A
by me, under the same open source license (unless I …
=> Fixed docker repositories and tags

charts/etos/charts/environment_provider/templates/deployment_api.yaml, charts/etos/charts/environment_provider/templates/deployment_worker.yaml, charts/etos/charts/etos-api/templates/deployment.yaml, charts/etos/charts/suite-starter/templates/deployment.yaml, charts/etos/templates/configmap.yaml, charts/etos/templates/sidecar_config.yaml, charts/etos/values.yaml
Fixes: #70 
Add filebeat that can be enabled in the helm charts. This is disabled by default.
Not that we do not install ELK in these helm charts and it has to be started outside of ETOS to work.
We should investigate whether we want to add ELK to ETOS as well.
Centralized logging is always good. This enabled the use of logstash if one has an instance up and running.
Possibly locking ourselves into ELK.
license and I have …
=> Add filebeat sidecars that can be enabled

cli/src/etos_client/lib/test_result_handler.py
fixes: #144 
Make sure we store all sub suites before we check if the main suites have finished.
The previous design was to keep the requests to ER to a minimum. Something that we should strive for. I found no obvious way of doing that in this PR.
We won't exit too fast, without downloading all logs anymore.
We hammer the ER a bit more now.
work with …
=> Fix a problem with all logs not being downloaded

charts/etos/charts/api/templates/deployment.yaml, charts/etos/charts/api/values.yaml, charts/etos/charts/environment-provider/charts/environment-provider-workers/templates/deployment.yaml, charts/etos/charts/environment-provider/charts/environment-provider-workers/values.yaml, charts/etos/charts/environment-provider/templates/deployment.yaml, charts/etos/charts/environment-provider/values.yaml, charts/etos/charts/suite-starter/templates/deployment.yaml, charts/etos/charts/suite-starter/values.yaml, charts/etos/templates/_helpers.tpl, charts/etos/templates/configmap.yaml, charts/etos/templates/database_secret.yaml, charts/etos/templates/rabbitmq_secret.yaml, charts/etos/values.yaml
N/A
Add the possibility to choose own secrets for rabbitmq and database.
I don't like the use of global, but having the users add the secret value to each chart would be too failure-prone.
This will allow users to deploy ETOS using other secret management than just regular kubernetes secrets. For example sealedsecrets.
None, really.
work with modifications, …
=> Make it possible to choose own secrets for db and rabbitmq

cli/src/etos_client/__main__.py, cli/src/etos_client/client.py
fixes: #156 
fixes: #114 
Exit when the ETOS API returns a client error (>=400<500).
I decided to remove the dependency to the ETOS library http wait method since it just caught every exception without allowing the ETOS client to handle certain errors.
This will allow the client to exit with a clear error message any time an error with input is caught by the ETOS API.
None that I can think of
license and I have the right …
=> Exit on client errors

cli/requirements.txt, cli/setup.cfg, cli/src/etos_client/__main__.py, cli/src/etos_client/downloader/__init__.py, cli/src/etos_client/downloader/downloader.py, cli/src/etos_client/etos/etos.py, cli/src/etos_client/logs/__init__.py, cli/src/etos_client/logs/logs.py, cli/src/etos_client/test_run/__init__.py, cli/src/etos_client/test_run/test_run.py
Depends-on: eiffel-community/etos-api#41
#148 
Connect to ETOS log proxy and get logs from running ETOS test runs.
For reviewing it is recommended to review the commits in isolation as the, now, Downloader was renamed from Logs to Downloader in order for this new module to be named Logs. The full diff looks weird :) 
I decided to keep the old messages as they are, since they still keep some valuable information. They should be removed in the future (speaking specifically about the announcer).
This will allow ETOS client to give better information when certain ETOS components are stuck in internal work.
Another dependency for logs and events. We should replace the event repository queries to use the ETOS API in the future.
By making a contribution to …
=> Logs from log proxy

cli/src/etos_client/downloader/downloader.py
In some cases, the names of the test case artifacts can become quite long, with various components and/or services in a test pipeline adding their "uniqueness" to the name to prevent conflicting names and potential data loss. If we're unlucky we override the max length of a filename and in that case the client crashes. A first step to handle this is to put the divide the test artifacts into folders named after the sub suite form which they originate. This will most likely fix any immediate artifact naming problems, but it would still be possible to exceed max length and cause a crash.
Truncating the name and adding yet another uniqness string to the filename would certainly be possible although by retaining the name we probably keep more of the intended file name information and don't …
=> Add sub suite folder to artifact download path

cli/src/etos_client/etos/etos.py
None
Retry on timeouts from requests as well. The requests.Timeout exception does not inherit TimeoutError which we already capture.
None
ETOS client will now retry on timeouts.
None that I can think of
permitted to submit under a different …
=> Add requests Timeout exception to should retry exceptions

cli/src/etos_client/downloader/downloader.py, cli/src/etos_client/event_repository/graphql.py, cli/src/etos_client/event_repository/graphql_queries.py, cli/src/etos_client/events/collector.py
N/A
Instead of getting all artifacts from the CONTEXT link to ActT, we get the artifacts from CAUSE links to sub suites instead.
Also increased the timeout for the downloader and the wait time between retries.
None that I could think of, really.
We expect artifacts to have CAUSE links to the sub suites, so now we wont miss these artifacts.
This change hammers the ER a little bit more than the CONTEXT link search, however the CONTEXT link search was a heavier query to the ER so I think it can be counted as the same.
(b) The contribution is based …
=> Collect artifacts from sub suites instead

cli/src/etos_client/test_run/test_run.py
N/A
When client is waiting for Activity Finished, we also need to check if the activity has been canceled, else this will in certain cases cause an unnecessary 24h wait until timeout is reached.
Nope
Test runs that don't get ahold of a test environment within the configure IUT checkout timeout period will not wait for 24h timeout to hit, instead they now react and exit on the Activity Cancel sent in this case.
None
license …
=> Add status check for Activity Canceled Event

cli/src/etos_client/logs/logs.py
#148 
Clean up timestamps to follow the OS timezone. ETOS library will always send the timestamp as UTC, so we will assume that is always the case.
None
No more time travel between ETOS services.
None
permitted to submit under a different …
=> Clean up timestamps from ETOS

cli/src/etos_client/announcer/announcer.py, cli/src/etos_client/downloader/downloader.py, cli/src/etos_client/event_repository/graphql.py, cli/src/etos_client/event_repository/graphql_queries.py, cli/src/etos_client/events/collector.py, cli/src/etos_client/events/events.py, cli/src/etos_client/logs/logs.py, cli/src/etos_client/start.py, cli/src/etos_client/test_run/test_run.py
fixes: #148 
Changed the logging in ETOS client to be more user focused.
Set log downloading to debug so it is not shown by default.
Changed the keep-alive message from ETOS to be more useful.
Stop logging the announcement events from ETOS.
Nothing really. I wanted to add some more information, but I decided that we want to keep the output minimal until we get complaints that something is missing.
Makes it a lot clearer what is going on in ETOS.
This change has some hard dependency to the SSE stream that we implemented in ETOS. If that one goes down, then the logging will not be as good.
have the right to submit it under the open …
=> Cleanup logging in etos

cli/src/etos_client/event_repository/graphql_queries.py, cli/src/etos_client/test_results/test_results.py
#148 
Add better messages when ETOS fails
None
Clearer what has happened
None
person who certified (a), (b) …
=> Add better failure messages when ETOS fails to start

cli/src/etos_client/test_run/test_run.py
N/A
There's a risk that the ETOS client deadlocks should the SSE client not properly shut down when an ETOS test run is finished. This extra check will give the SSE client >5 minutes to shut down and, if it doesn't, will force shutdown of the loop.
I do believe that the change to our v1 protocol fixes/mitigates this problem, however there's still a small risk so I wanted to add it anyway.
Reduces the number of deadlocks we get in the client.
There could be a problem with the client exiting early, without getting all logs downloaded. I did give the client 5 minutes to finish, however, so that shouldn't be a real problem.
have the …
=> Fix a potential deadlock

.github/workflows/update-release.yml
#197 
This workflow will check out all ETOS components that are defined in the release manifest, get their latest release tag and update the manifest with these tags.
It is manually triggered right now instead of automatic. I decided against automated updates as they are more complex and there may be dependencies between components that require them to be updated at the same time.
This will allow us to semi-automatically update the ETOS release versions.
None that I can think of
of …
=> Add a manually triggered workflow that updates release

manifests/etcd/kustomization.yaml, manifests/etcd/service.yaml, manifests/etcd/statefulset.yaml, manifests/master/kustomization.yaml
N/A
We are looking into replacing redis with etcd in ETOS. This change is in preparation for that. Making sure that we have an ETCD cluster deployed that we can play around with.
I could have skipped adding etcd by default and just having a cluster deployed when I play around with etcd. The problem with that however is that we may end up where we are with redis. I.e. we do not deploy redis with ETOS at the moment.
This change would also make it easier for us to actually start using etcd on the side, verifying in a real environment that it works as we expect.
This change will allow us to start playing around with and verify etcd as a database replacement in ETOS.
Adding this now, when we are not sure we want to use it (even if we are quite sure) adds, potentially, unnecessary pods into our …
=> Adding an etcd cluster

cli/requirements.txt, cli/setup.cfg, cli/src/etos_client/downloader/downloader.py, cli/src/etos_client/etos/etos.py, cli/src/etos_client/start.py
- [etosctl using legacy code for log download](https://github.com/eiffel-community/etos/issues/211)
This change steps up the version of etos_lib to 4.0.0 and modifies the log downloader to use the new HTTP client from etos_lib.
permitted to submit …
=> Use etos_lib HTTP client for log download

cli/requirements.txt, cli/setup.cfg
Add missing dependency to pydantic which causes etosctl failure at start.
person who certified (a), (b) or …
=> Add pydantic dependency

cli/src/etos_client/events/events.py
- [pydantic validation errors when starting a testrun](https://github.com/eiffel-community/etos/issues/214)
Optional fields need to be given default values in order for the pydantic validation to work properly.
permitted to submit under a …
=> Fix pydantic validation for pydantic 2.6.x

cli/src/etosctl/__main__.py
fixes: #219 
Set the log level of gql to WARNING so that users of the client don't get too much debuggy information
None
We could miss messages that are being sent on the INFO level. But I do believe that we want to control the output as much as possible, so we should detect the issues and create our own messages that are clear for our users.
work with …
=> Set gql log level to WARNING instead of INFO/DEBUG

source/index.rst, source/sse.rst
#190
Document the way we want to use SSE
None
None
person who certified (a), (b) or (c) and I have not …
=> Add the suggested SSE protocol to the documentation

cli/src/etos_client/announcer/announcer.py, cli/src/etos_client/events/collector.py, cli/src/etos_client/test_run/test_run.py
#238 
ETOS is doing a lot of requests to the event repositories. This is not scalable at all and we need to reduce the amount of queries we are doing and start working on a better solution.
We could go to the final solution right away, but that is quite a ways away and we should try to reduce the queries now.
We will be missing some test case information with this change, this is just flavor and not necessary for an ETOS testrun.
There will also be a few logs that may come at weird times such as "waiting for test suite to start" when you can clearly see from the SSE logs that the suite has started. This should be fine in my opinion.
(a) The contribution was created in whole or in part by me and …
=> Attempt to reduce the number of ER requests

cli/src/etos_client/downloader/downloader.py
- https://github.com/eiffel-community/etos/issues/249
This change sets the max number of simultaneous connections to 10, which equals the default limit in the requests library.
in the …
=> Limit max number of connections to log area

cli/pyproject.toml
- https://github.com/eiffel-community/etos/issues/255
This change adds a `readme` field to `pyproject.toml` of the etos Python package. This is intended to fix the failing Pypi publishing action.
Pypi is complaining about `long_description`, however it seems to have been replaced with `readme`.
by me, …
=> add readme field to pyproject.toml

cli/src/etos_client/test_results/test_results.py
Since we no longer collect information/events on subsuites
the logic fo logging messages about failures in sub suites
was not workin properly. This resulted in incorrect error
message when a suite successfully executed but had test case
failures in it.
Log message will be a tad less detailed in it's information (e.g no information about the number of sub suites)
license and I have the right under that license to submit …
=> Log the correct fail/error message

cli/pyproject.toml, cli/requirements.txt, cli/src/etos_client/downloader/downloader.py, cli/src/etos_client/sse/protocol.py, cli/src/etos_client/test_results/test_results.py, cli/src/etos_client/test_run/test_run.py, cli/tox.ini, source/sse.rst
Listen for Report and Artifact events instead of polling the log area server when downloading files.
None
None
(c) The contribution was provided directly to me by some …
=> Enable downloading from internal report and artifact events

cli/pyproject.toml, cli/setup.py
- https://github.com/eiffel-community/etos/issues/284
This change fixes the compatibility problem with tox/setuptools by moving the options from `pyproject.toml` to `setup.py`.
in the …
=> Compatibility fix for latest tox and setuptools

cli/pyproject.toml, cli/setup.py, cli/src/etos_client/etos/etos.py, cli/tox.ini
- https://github.com/eiffel-community/etos/issues/208
This change fixes several fields to `cli/pyproject.toml` that were incorrect since the migration from `setup.cfg` to `pyproject.toml`.
permitted to submit under a different license), as …
=> Fix incorrect fields in cli/pyproject.toml

cli/src/etos_client/downloader/downloader.py
Fix the names when duplicate files exist.
it. …
=> Fix the names when duplicate files exist

.github/workflows/add-manifest-to-release.yml, .github/workflows/generate-manifest.yml
One workflow for generating an installer for each commit.
One workflow for uploading the installer to each release.
(c) The contribution was provided directly to me by …
=> Add workflows for the ETOS Kubernetes controller

internal/etos/suitestarter/suitestarter.go
The service account was created using the suite runner name and the template for the ESR used that name plus the suffix "-template" to name the ESR template. That same name was then also used as the SA for the ESR, a SA that does not exist because it was not created with the suffix.
The fix here is to grab two names for the template, one is the name of the template and the other is the name of service account.
license and …
=> Properly set the service account name in ESR template

internal/controller/environment_controller.go, internal/controller/environmentrequest_controller.go, internal/controller/jobs.go, internal/controller/testrun_controller.go
- https://github.com/eiffel-community/etos/issues/262
This change adds generated names for environment provider jobs and changes the logic for matching containers in terminationLog().
in …
=> Generated environment provider jobs

internal/etos/suitestarter/suitestarter.go
- https://github.com/eiffel-community/etos/issues/300
This change adds reconciliation of Suite Runner service account, role and rolebinding. …
=> add reconcile for suite runner role and role binding

internal/controller/testrun_controller.go
Now when ESR is able to retrieve testrun resources from Kubernetes directly we can remove the TERCC environment variable from the testrun controller. 
(c) The …
=> Remove TERCC from testrun controller

internal/controller/environmentrequest_controller.go
- https://github.com/eiffel-community/etos/issues/264
This change allows multiple environment provider jobs during job status checks in `EnvironmentRequestReconciler`. …
=> Environment request: multiple provider jobs in status checks

api/v1alpha1/environment_types.go, config/crd/bases/etos.eiffel-community.github.io_environments.yaml, internal/controller/environment_controller.go, internal/etos/etos.go
Add some environment variables for the environment releaser, add permissions and show environment termination description when doing kubectl get environment.
The permissions are added to be used by the next generation environment provider which is more of a pipeline orchestrated by ETOS in order to keep much stricter control over how environments are released in case of errors.
license and I have the right under that …
=> Add environment variables and show environment description

cli/src/etos_client/etos/v0/schema/request.py, cli/src/etos_client/etos/v0/subcommands/start.py
fixes: #221 
Pass an activity triggered event ID to the ETOS API if supplied.
Will take an input parameter or read ActT from an environment variable.
This change only affects etos v0 since v1alpha does not yet support causal events #341 
permitted …
=> Pass parent activity to ETOS API if added

.github/workflows/generate-manifest.yml, Makefile, README.md, api/v1alpha1/cluster_types.go, config/crd/bases/etos.eiffel-community.github.io_clusters.yaml, config/manager/kustomization.yaml, config/samples/etos_v1alpha1_cluster.yaml, internal/etos/suitestarter/suitestarter.go, manifests/controller/install.yaml, skaffold.yaml
- https://github.com/eiffel-community/etos/issues/343
This pull request changes all docker image references from `nordix.org/eiffel` to `ghcr.io/eiffel-community`.
(c) …
=> Migrate container images to ghcr.io

internal/controller/testrun_controller.go
- https://github.com/eiffel-community/etos/issues/277
- https://github.com/eiffel-community/etos-api/pull/97
- https://github.com/eiffel-community/etos-api/pull/98
This change removes the old unused labels `id` and `app` from the testrun controller.
by me, under the same open source license (unless I …
=> testrun controller: remove unused labels

README.md, source/getting_started/step-by-step.rst
- https://github.com/eiffel-community/etos/issues/354
This change updates the documentation by removing redis mentions since it has been replaced by etcd which is installed as a part of ETOS.
permitted to submit under a different license), as …
=> Remove redis from the documentation

cli/src/etos_client/etos/v0/schema/request.py, cli/src/etos_client/etos/v1alpha/etos.py, cli/src/etos_client/etos/v1alpha/schema/__init__.py, cli/src/etos_client/etos/v1alpha/schema/request.py, cli/src/etos_client/etos/v1alpha/schema/response.py
- https://github.com/eiffel-community/etos/issues/359
The change modifies the `from_args` method to handle missing optional arguments more robustly by using conditional expressions to set default values. This ensures that the `RequestSchema` is created with appropriate default values when these arguments are not provided.
work with modifications, whether …
=> fix KeyError when optional CLI args are omitted

internal/controller/testrun_controller.go
When running with an external (to ETOS) messagebus we don't want to prepend cluster. Only prepend cluster name when a messagebus has been deployed by ETOS.
(c) The …
=> Only prepend cluster on messagebuses if deployed by ETOS

internal/etos/suitestarter/suitestarter.go
This change sets requests and limits for containers in the Runner template. This should increase scalability in environments where Kubernetes has high default memory allocation unless requests/limits are explicitly set.
permitted to submit under a …
=> Set requests/limits for Suite Runner initContainers

internal/controller/environmentrequest_controller.go
The current implementation tries to get passwords as strings in the environmentRequest spec, however if we try to add passwords from secrets or configmaps then that won't work.
Fix so that the environmentrequestcontroller gets passwords via the Var.Get() method.
by me, under the same open source …
=> Actually get passwords from the config for environmentrequests

internal/controller/testrun_controller.go
- https://github.com/eiffel-community/etos/issues/372
This change removes the assumption about etcd hostname from the testrun controller.  …
=> testrun controller: remove hostname assumption for etcd

internal/controller/environmentrequest_controller.go
fixes: #362 
When an environment request gets deleted, delete all environments connected to it and wait for them to be deleted before getting removed from Kubernetes. This will ensure that deletions of environment requests always propagate to the environments. Before this only deletion of testruns would, sometimes, propagate to environments.
This also fixes another issue in that the environment controller has a dependency to the environment request but it does not always exist in Kubernetes due to not blocking its deletion.
Nope
More objects will get stuck if an environment cannot be released but it's better than crashing.
have …
=> Block environmentrequest deletion and propagate deletes

api/v1alpha1/environmentrequest_types.go, config/crd/bases/etos.eiffel-community.github.io_environmentrequests.yaml, internal/controller/environmentrequest_controller.go, internal/controller/testrun_controller.go
- https://github.com/eiffel-community/etos/issues/374
This change makes sure all environment variables are passed from `EnvironmentProviderJobConfig` to the environment provider job.
in …
=> pass missing variables to environment provider job

internal/controller/testrun_controller.go, internal/etos/suitestarter/suitestarter.go
Also add CPU limits and requests in the suite runner template
I probably added too high limits for the initContainers, but since the pod will have its real limit and requests set to the highest request we will always get the LogListener container + the ESR container anyways because it's higher than the initContainers.
More on how Kubernetes calculates resources can be found [here](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resource-sharing-within-containers)
When Kubernetes support for [Pod resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#example-2) is generally available we should move over to use those.
(a) The contribution was …
=> Set limits on all containers in ESR

internal/etos/database.go
I found no issue on this, but related to #387 
Update the ETCD version to the latest available at the time of this PR (v3.5.19).
Updated how we start the container so that it works with the newer version, but also went through and applied a few changes as per this documentation: https://etcd.io/docs/v3.5/op-guide/kubernetes/
Nothing really
I don't know how this will deploy in clusters that are running the old v3.3.8 version.
of my knowledge, is covered under an appropriate open …
=> Update ETCD version and clean up statefulset

cli/src/etos_client/etos/v0/etos.py, cli/src/etos_client/etos/v0/test_run/test_run.py, cli/src/etos_client/etos/v1alpha/etos.py, cli/src/etos_client/etos/v1alpha/subcommands/start.py, cli/src/etos_client/etos/v1alpha/test_run/__init__.py, cli/src/etos_client/etos/v1alpha/test_run/test_run.py, cli/src/etos_client/sse/v2alpha/__init__.py, cli/src/etos_client/sse/v2alpha/client.py, cli/src/etos_debug/__init__.py, cli/src/etos_debug/command.py, internal/controller/testrun_controller.go
Add a testrun client for ETOS v1alpha that exclusively uses SSE v2alpha.
Call the v0 testrun client if SSEv1 is used.
Update to use the ETOS library messaging protocol.
Add a debug client for ETOS that can be used with SSEv2
permitted to submit …
=> Add ssev2 client

internal/etos/api/api.go, internal/etos/suitestarter/suitestarter.go, internal/extras/eventrepository.go, internal/extras/messagebus.go, internal/extras/mongodb.go, internal/extras/rabbitmq.go
By adding or updating an annotation to the spec Kubernetes will automatically recreate the deployments and statefulsets causing the pods to restart and get the new configurations. This way of doing it is the same way as kubectl rollout restart.
I've not been able to test this yet since my local environment is busted at the moment so this change may not work yet
None that I could think of.
The one thing I thought of (and am going to test) is that we might get stuck in a reconcile loop. I don't know how or why but we've had these loops before and we need to verify that this change does not cause any.
have the right to submit it …
=> Restart deployments and statefulsets if configurations have changed

internal/etos/api/api.go, internal/etos/suitestarter/suitestarter.go, internal/extras/eventrepository.go, internal/extras/mongodb.go, internal/extras/rabbitmq.go
fixes: #403 
If there are no annotations on a deployment we cannot just add to the map, we need to create the map first.
(c) The contribution was provided directly to me …
=> Fix a crash that we get when the Annotations map is nil

cli/src/etos_client/etos/v1alpha/test_run/test_run.py, cli/src/etos_client/sse/v2alpha/client.py, cli/src/etos_debug/command.py
- https://github.com/eiffel-community/etos/issues/417
The change is a temporary workaround for the mentioned issue. It will be reverted when this etos-library change is integrated: https://github.com/eiffel-community/etos-library/pull/48
permitted …
=> etos_client: disable imports from etos_lib.messaging

internal/etos/suitestarter/suitestarter.go
There was a reference to the log-listener image that was hard coded, replaced it with the proper
dynamic reference.
(c) The contribution was provided directly to me by …
=> Remove hard coded image name for log listener

cli/pyproject.toml
Github CI fails to build the ETOS Client Python package:
https://github.com/eiffel-community/etos/actions/runs/16877339988/job/47804866576
```
File "/tmp/build-env-bynyi_ut/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 123, in infer_version
result.apply(dist)
File "/tmp/build-env-bynyi_ut/lib/python3.9/site-packages/setuptools_scm/_integration/version_inference.py", line 48, in apply
_version_missing(config)
File "/tmp/build-env-bynyi_ut/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 188, in _version_missing
raise LookupError(error_msg)
LookupError: setuptools-scm was unable to detect version for /home/runner/work/etos/etos/cli.
```
This change adds `tool.setuptools_scm` section in ETOS Client's `pyproject.toml` to fix the Git version …
=> setuptools_scm root path in cli/pyproject.toml
