eiffel-community/etos

- source/coderules.rst
N/A
Make the links part of the text
Could stay as it was
Easier to read the document
person who certified …
> Clean up links in the coderules document

- source/concepts/execution_space.rst
- source/concepts/index.rst
- source/concepts/iut.rst
- source/concepts/log_area.rst
- source/getting_started/step-by-step.rst
- source/getting_started/tercc.rst
- source/index.rst
- source/services/etos_client.rst
- source/services/etos_environment_provider.rst
Fixes: #11 
Add a checklist for setting up ETOS
Instead of a checklist have a large written guide. Both should exist, but this should be seen as a short-form so that you do not miss a step.
Easier to know what needs to be setup and easier to not forget a step.
Might be too little information on each step and the size of the checklist may be a bit daunting.
work …
> Adding a checklist to follow when setting up ETOS

- source/index.rst
- source/release_process.rst
None
Add a release process to explain how ETOS is released and what to expect from us.
There are multiple designed, but during discussion with maintainers this was the proposed one.
Easier for us to keep track and users will be happy knowing what happens in the world of ETOS.
We must stick to it :)
by …
> Added a release process for ETOS.

- source/index.rst
- source/services/etos_environment_provider.rst
#33 
eiffel-community/etos-environment-provider#18
Added documentation
person who certified (a), (b) or (c) …
> Add documentation for the IUT provider preparation step

- source/getting_started/tercc.rst
Changed "checkout" to "clone".
N/A
Fixed a typo in the documentation.
N/A
It will be easier to create an ETOS Test collection.
N/A
(c) The contribution was provided …
> Fixed a typo

- charts/etos/charts/environment_provider/templates/_helpers.tpl
- charts/etos/charts/environment_provider/values.yaml
- charts/etos/charts/etos-api/values.yaml
- charts/etos/charts/suite-starter/values.yaml
- charts/etos/templates/_helpers.tpl
- charts/etos/values.yaml
N/A
Allow tag overrides on dev
Change so that images are always downloaded from eiffel instead of eiffel-playground
(c) The contribution was provided directly to me by …
> Allow overrides on tags even on dev

- README.rst
N/A
Minor grammar fix.
None.
Polish.
None.
it. …
> Minor grammar fix in README

- charts/etos/templates/configmap.yaml
- charts/etos/values.yaml
#88 
Add the routing key describe in the ETOS Library change for #88 
None
N/A
None
person who certified …
> Add routing key tag parameter

- charts/etos/Chart.yaml
- charts/etos/charts/environment_provider/Chart.yaml
- charts/etos/charts/etos-api/Chart.yaml
- charts/etos/charts/suite-starter/Chart.yaml
- charts/etos/values.yaml
N/A
Update to all latest versions of components.
This next release will be a major release, 2.0.0 due to #91 
(c) The contribution was provided directly to me by some …
> Update to latest versions of each component

- charts/etos/templates/configmap.yaml
- charts/etos/values.yaml
- source/getting_started/tercc.rst
- source/services/etos_test_runner.rst
fixes: #92 
Remove CLM events from ETOS completely.
This was decided in the first Issue.
ETOS should not decide the confidence level for software. It should decide the test results based on tests executed.
None. This change has been communicated. …
> Completely remove the sending of CLM events

- charts/etos/Chart.yaml
- charts/etos/charts/environment_provider/Chart.yaml
- charts/etos/charts/etos-api/Chart.yaml
- charts/etos/charts/suite-starter/Chart.yaml
- charts/etos/values.yaml
N/A
* API: 1.25.0
* Test Runner: 2.0.0
* Suite Starter: 1.26.0
* Environment Provider: 1.27.0
* Suite Runner: 2.0.0
None
Latest and greatest
None …
> Update to latest versions of ETOS components

- charts/etos/Chart.yaml
- charts/etos/charts/api/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/charts/suite-starter/Chart.yaml
- charts/etos/values.yaml
N/A
* etos-api version 1.26.0
* etos-suite-starter 1.27.0
* etos-suite-runner 2.0.1
* etos-environment-provider 1.29.0
* etos-environment-provider-worker version 1.29.0
* etos-test-runner version 2.0.0
None
New versions
None
permitted to submit …
> Update to version 4.0.0 of ETOS

- charts/etos/Chart.yaml
- charts/etos/charts/api/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/charts/suite-starter/Chart.yaml
- charts/etos/values.yaml
N/A
* etos-api version 1.27.0
* etos-suite-starter 1.28.0
* etos-suite-runner 2.1.0
* etos-environment-provider 1.30.0
* etos-environment-provider-worker version 1.30.0
* etos-test-runner version 2.1.0
None
Latest and greatest
None
permitted to …
> Update to 4.1.0 of ETOS

- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
N/A
Update ETOS to use the latest version of the Environment Provider
* Environment Provider: 1.32.0
None
Latest bugfixes and patches
None …
> Update ETOS Environment Provider to latest version

- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
#120 
Update to the latest version of environment provider which fixes #120 
person who certified (a), (b) …
> Update to version 1.32.2 of environment provider

- charts/etos/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
N/A
Set the chart and app versions of ETOS. …
> Prepare ETOS for release

- charts/etos/Chart.yaml
N/A
appVersion for ETOS does not provide any additional information so it was removed.
Updated the version of the ETOS chart to 4.3.0
(c) The contribution was provided …
> Set minor tag instead of micro and remove appVersion from ETOS

- charts/etos/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/values.yaml
#126 
#124 
Added support for multiple test suites in ETOS
person who certified (a), (b) or (c) and I have …
> Update to latest versions of components

- charts/etos/Chart.yaml
- charts/etos/charts/api/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/values.yaml
#22 
Update to the latest versions of components, preparing for sequential execution and allowing for permutation testing.
None. We should always update components.
We should always update components.
None
permitted to submit under a different …
> Update to new versions of components

- charts/etos/values.yaml
None
Fix a bug with ESR
None
None
None
it.
(d) …
> Bugfix for ETOS suite runner

- charts/etos/values.yaml
#139 
Fixes hanging ESR jobs
it.
(d) I …
> Update to new version of ETOS suite runner

- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/values.yaml
#147 
Updating to latest versions
N/A
N/A
N/A …
> New versions of environment provider and suite runner

- charts/etos/values.yaml
N/A
Update ESR to 2.4.2
N/A
N/A
N/A
it.
(d) I …
> New version of Suite Runner

- charts/etos/templates/database_secret.yaml
N/A
Set database host and port in stringData
Data i b64 encoded making hard to, at a glance, see what it is.
Easier to read
None
(c) The contribution was provided …
> Database host and port should be stringData not b64

- charts/etos/charts/suite-starter/Chart.yaml
N/A
Update to latest version
N/A
N/A
N/A
it. …
> Update to version 1.29.0 of suite starter

- charts/etos/values.yaml
N/A
Update ETR to 3.0.0
None
N/A
N/A
it.
(d) I …
> Update ETR to 3.0.0

- .gitignore
- cli/src/etos_client/lib/graphql.py
- cli/src/etos_client/lib/graphql_queries.py
- cli/src/etos_client/lib/test_result_handler.py
Refactoring
Clean up ER requests with some helper methods and a dict class to make code cleaner.
None
Cleaner code
None
(c) The contribution was provided directly to me …
> Clean up ER requests and make them easier to understand

- cli/src/etos_client/etos/schema.py
based on: #164 
fixes: #165 
Stop validating identity and pass it onto the ETOS API to validate instead.
None
Will allow for more complex regexes when starting ETOS.
Will allow users to do complex regexes which is costly on the event repository. …
> Allow packageurl regex

- charts/etos/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/charts/suite-starter/Chart.yaml
- charts/etos/values.yaml
#165
#163 
#78 
Prepare for the 4.9.0 release.
N/A
N/A
N/A
person who certified (a), (b) or (c) and I have …
> Preparations for the 4.9.0 release of ETOS

- cli/src/etos_client/__main__.py
None
Added a try: finally: to make sure that we always stop the log downloader.
None
The log downloader won't hang when activity canceled has been found.
None
(c) The …
> Fix a bug with ETOS client hanging

- cli/src/etosctl/__main__.py
- cli/src/etosctl/command/command.py
None
Fix a problem with the compatibility "layer" and etos client. We forgot to pass argv to the etosctl command.
None
Backwards compatible
None …
> Fix a problem with the etos client backwards compatiblity

- cli/src/etos_client/announcer/announcer.py
#182 
Add passed test cases to keep-alive message.
None
Clearer message in regards to the total test case count
None
(c) The contribution was provided directly to me by …
> Add number of passed test cases to output

- cli/src/etos_client/logs/logs.py
#182 
Make sure we don't raise exceptions if we cannot parse the JSON struct from ETOS.
There are several. Right now we drop messages that are not able to be parsed. We could make it so that the message is tried again, but that may bring on an infinite loop in the ETOS client that we don't want to deal with.
This will allow the client to run even though there are network hiccups and the like
We are hiding the underlying problem, instead of fixing it.
of my knowledge, is covered …
> Catch errors from sse

- charts/etos/Chart.yaml
- charts/etos/charts/api/Chart.yaml
- charts/etos/charts/environment-provider/Chart.yaml
- charts/etos/charts/environment-provider/charts/environment-provider-workers/Chart.yaml
- charts/etos/charts/suite-starter/Chart.yaml
- charts/etos/templates/rabbitmq_secret.yaml
- charts/etos/values.yaml
N/A
Prepare for the 5.0.0 release of ETOS.
it. …
> Prepare for the 5.0.0 release of ETOS

- charts/etos/charts/api/charts/sse/Chart.yaml
- charts/etos/charts/api/charts/sse/templates/NOTES.txt
- charts/etos/charts/api/charts/sse/templates/_helpers.tpl
- charts/etos/charts/api/charts/sse/templates/deployment.yaml
- charts/etos/charts/api/charts/sse/templates/hpa.yaml
- charts/etos/charts/api/charts/sse/templates/service.yaml
- charts/etos/charts/api/charts/sse/templates/serviceaccount.yaml
- charts/etos/charts/api/charts/sse/values.yaml
- charts/etos/templates/ingress.yaml
- charts/etos/values.yaml
- cli/src/etos_client/etos/etos.py
- cli/src/etos_client/logs/logs.py
- cli/src/etos_client/start.py
eiffel-community/etos-api#44
Update to use the new SSE service instead of the ETOS API implemenation.
No alternatives to the new service. For the update that ETOS client now knows about the API endpoints, we could have had the ETOS API return the endpoints, but it just feels like a bit of a hassle to update the client if we do that.
This will reduce the load on the ETOS API, which is already on its knees.
Another service in ETOS. Not a big problem.
The fact that we assume endpoints in the Client may be a problem if users deploy ETOS differently from what we assume. …
> New sse service

- manifests/release/kustomization.yaml
N/A
Preparation for new release.
This is a major release since helm charts are removed.
person who …
> Prepare for 6.0.0 release of ETOS

- manifests/release/kustomization.yaml
N/A
Update the release versions
it.
(d) I …
> Update release versions

- manifests/release/kustomization.yaml
N/A
Let the components decide their dependencies
Could keep it as is, but this will cause a mismatch between expected and actual versions.
Will be harder to make version mistakes
Won't be able to see all versions in one place
permitted to submit …
> Let component with sub-dependencies decide the versions of those

- manifests/base/kustomization.yaml
#197 
eiffel-community/etos-suite-starter#29
eiffel-community/etos-suite-runner#47
Add the new ESR manifest to the base manifests
None
This will allow the ESR to have some good CI
in the …
> Add etos suite runner manifest

- manifests/base/kustomization.yaml
- manifests/master/kustomization.yaml
- manifests/release/kustomization.yaml
N/A
Force ETOS release to point to git tags on the component repositories.
There is none
Released ETOS won't get any manifest updates automatically
None
(c) The …
> Force versions by pointing to git tags instead

- manifests/release/kustomization.yaml
#200 
The release 2.0.1 of suite starter does not have any kustomize manifests. These were added in 2.1.0, which has more changes that are not something we want just yet. …
> Set a SHA for suite starter

- manifests/release/kustomization.yaml
N/A
With the #200 update we change back main to the old v6.0.0 versions of components. After that change has been tagged, we should merge this to get the expected staging versions.
in …
> Latest versions

- manifests/release/kustomization.yaml
None
Add ETCD to release manifest
it.
(d) I …
> Add ETCD to the release manifest

- manifests/master/kustomization.yaml
fixes: #222 
Remove the environment provider deployment for the master manifests.
None!
None!
person who …
> Remove the hosted environment provider

- .github/workflows/update-release.yml
- manifests/release/kustomization.yaml
#223 
Remove the hosted environment provider next release
person who certified (a), (b) or (c) and I have …
> Remove the hosted environment provider next release

- source/database.rst
- source/index.rst
#205
Adding documentation for the database structure that we are to use.
Too many to list here
None yet …
> Add ETCD paths to documentation

- manifests/etcd/statefulset.yaml
N/A
Increase the disk size for ETCD since 1gb is quite low. For production deployments it should probably be increased even more.
I could increase it even more, but we don't know how others use this so we don't want to ruin anything.
More disk …
> Increase default disk size for ETCD

- .github/workflows/build-publish.yml
Build the ETOS client and publish to pypi when creating a new git tag
person who certified (a), (b) or (c) …
> Add a build publish workflow for etos client

- cli/src/etos_client/downloader/downloader.py
Make sure that the checksums are optional.
it. …
> Make the checksum on a Downloadable optional

- cli/src/etos_client/downloader/downloader.py
Actually make sure that the checksums are optional, I.e. correctly set them as an empty dict.
person who …
> Make the checksums optional all the way up the stack

- .github/workflows/generate-manifest.yml
it.
(d) I understand and agree that this …
> Ignore errors when deleting directory

- .github/workflows/add-manifest-to-release.yml
- .github/workflows/generate-manifest.yml
Make sure we build the docker and use the correct version in the install manifest.
person who certified …
> Add docker build and copy install manifest to manifests

- internal/etos/api/logarea.go
- internal/etos/api/sse.go
eiffel-community/etos-api#94
Remove STRIP_PREFIX, it should no longer be necessary.
person who certified …
> Remove the STRIP_PREFIX option from API services

- internal/controller/environmentrequest_controller.go
- https://github.com/eiffel-community/etos/issues/263
This change adds environment request jobs status updates on errors during provider check and during environment provider reconciliation.
permitted to submit under a different license), as …
> Update environment request status on errors

- config/manager/manager.yaml
This change sets an increased limit for the controller manager container.
person who certified (a), (b) or …
> Increase controller container memory limit

- .github/workflows/generate-manifest.yml
Split the manifests into namespace, namespaced and cluster manifests. These can be used if one wants to separate the deployments of certain levels of resources.
The install.yaml file will still be created so I don't see any drawbacks of this. …
> Generate manifests that are split to namespaced and cluster

- internal/controller/provider_controller.go
- https://github.com/eiffel-community/etos/issues/349
This change modifies the logic in provider reconciliation to make sure a health check  and a status update is done on first reconciliation.
permitted to submit under a different license), as …
> Fix empty status bug after provider reconciliation

- internal/controller/environment_controller.go
fixes: #369 
Pass in the ETCD database host from the Cluster resource if it exists.
I really did not want to get the Cluster resource in the environment_controller, but I cannot find a way to get rid of it
The fact that we get the Cluster resource from Kubernetes.
by me, under the same open source …
> Make sure we pass the correct ETCD host if deployed by cluster

- internal/controller/environment_controller.go
- internal/controller/testrun_controller.go
#372 
Make sure we also pass the cluster name if the cluster deployed the ETCD database.
person who …
> Make sure we pass the cluster name if cluster deployed etcd

- internal/controller/environment_controller.go
fixes: #377 
These were accidentally removed in #339 when testing a new pipeline based environment provider.
I did not add RabbitMQ parameters as per the issue, instead I fixed it so that the correct script is executed.
permitted to submit under a …
> Re-add the command and args for environment releaser

- internal/etos/database.go
- manifests/etcd/statefulset.yaml
The latest tag was removed from quay because the ETCD maintainers don't want to update it. The version that was tagged with latest was v3.3.8 so I set this one to fix the problem ASAP.
I will write an issue to upgrade to the latest version of ETCD.
by me, under the same open source license (unless I …
> Set an explicit ETCD version

- .github/workflows/build-publish.yml
Version 2.1.0 of gh-action-sigstore-python used upload-artifact v3,
which seems to be have removed. v3.0.0 uses v4 instead.
(c) The contribution was provided directly to …
>  Update the sigstore action version

- api/v1alpha1/provider_webhook.go
The secret may contain passwords
it.
(d) I …
> Let's not log the secret to stdout

- internal/controller/testrun_controller.go
- internal/etos/suitestarter/suitestarter.go
Reverts eiffel-community/etos#395
> Revert "Adjust CPU limits for Suite Runner"

- cli/src/etos_client/etos/v1alpha/etos.py
#383 
Fixed so that we actually break out of the while loop when there is a result from tracking a testrun. …
> The ETOS v1alpha client would never shutdown
